language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=Django==1.3.4
  - DJANGO_VERSION=Django==1.3.7
  - DJANGO_VERSION=Django==1.4.3
  - DJANGO_VERSION=Django==1.4.4
  - DJANGO_VERSION=Django==1.4.5
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.5.1

# command to install dependencies
install:
  - pip install --use-mirrors -r test-requirements.txt
  - pip install --use-mirrors $DJANGO_VERSION

# command to run tests

script:
  - python run_tests.py