language: python

python:
  - '2.6'
  - '2.7'

env:
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.5.1
  - DJANGO_VERSION=Django==1.5.2
  - DJANGO_VERSION=Django==1.5.3
  - DJANGO_VERSION=Django==1.5.4
  - DJANGO_VERSION=Django==1.5.5
  - DJANGO_VERSION=Django==1.5.6
  - DJANGO_VERSION=Django==1.5.7
  - DJANGO_VERSION=Django==1.5.8
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.6.1
  - DJANGO_VERSION=Django==1.6.2
  - DJANGO_VERSION=Django==1.6.3
  - DJANGO_VERSION=Django==1.6.4
  - DJANGO_VERSION=Django==1.6.5
  - DJANGO_VERSION=Django==1.7
  - DJANGO_VERSION=Django==1.7.1
  - DJANGO_VERSION=Django==1.7.2
  - DJANGO_VERSION=Django==1.7.3
  - DJANGO_VERSION=Django==1.7.4
  - DJANGO_VERSION=Django==1.7.5
  - DJANGO_VERSION=Django==1.7.6
  - DJANGO_VERSION=Django==1.7.7
  - DJANGO_VERSION=Django==1.7.8
  - DJANGO_VERSION=Django==1.7.9
  - DJANGO_VERSION=Django==1.7.10
  - DJANGO_VERSION=Django==1.8
  - DJANGO_VERSION=Django==1.8.1
  - DJANGO_VERSION=Django==1.8.2
  - DJANGO_VERSION=Django==1.8.3
  - DJANGO_VERSION=Django==1.8.4


# command to install dependencies
install:
  - pip install --use-mirrors -r test-requirements.txt
  - pip install --use-mirrors $DJANGO_VERSION

# command to run tests

script:
  - python run_tests.py

matrix:
  exclude:
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.1
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.2
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.3
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.4
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.5
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.6
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.7
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.8
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.9
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.7.10
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.8
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.8.1
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.8.2
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.8.3
    - python: '2.6'
      env: DJANGO_VERSION=Django==1.8.4
