language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=Django==1.4.2
  - DJANGO_VERSION=Django==1.4.3
  - DJANGO_VERSION=Django==1.4.4
  - DJANGO_VERSION=Django==1.4.5
  - DJANGO_VERSION=Django==1.4.6
  - DJANGO_VERSION=Django==1.4.7
  - DJANGO_VERSION=Django==1.4.8
  - DJANGO_VERSION=Django==1.4.9
  - DJANGO_VERSION=Django==1.4.10
  - DJANGO_VERSION=Django==1.4.11
  - DJANGO_VERSION=Django==1.4.12
  - DJANGO_VERSION=Django==1.4.13
  - DJANGO_VERSION=Django==1.4.14
  - DJANGO_VERSION=Django==1.4.15
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.5.1
  - DJANGO_VERSION=Django==1.5.2
  - DJANGO_VERSION=Django==1.5.3
  - DJANGO_VERSION=Django==1.5.4
  - DJANGO_VERSION=Django==1.5.5
  - DJANGO_VERSION=Django==1.5.6
  - DJANGO_VERSION=Django==1.5.7
  - DJANGO_VERSION=Django==1.5.8
  - DJANGO_VERSION=Django==1.5.9
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.6.1
  - DJANGO_VERSION=Django==1.6.2
  - DJANGO_VERSION=Django==1.6.3
  - DJANGO_VERSION=Django==1.6.4
  - DJANGO_VERSION=Django==1.6.5
  - DJANGO_VERSION=Django==1.6.6
  - DJANGO_VERSION=Django==1.6.7
  - DJANGO_VERSION=Django==1.7
  - DJANGO_VERSION=Django==1.7.1
  - DJANGO_VERSION=Django==1.7.2
  - DJANGO_VERSION=Django==1.7.3
  - DJANGO_VERSION=Django==1.7.4
  - DJANGO_VERSION=Django==1.7.5
  - DJANGO_VERSION=Django==1.7.6
  - DJANGO_VERSION=Django==1.7.7
  - DJANGO_VERSION=Django==1.7.8
  - DJANGO_VERSION=Django==1.7.9
  - DJANGO_VERSION=Django==1.7.10
  - DJANGO_VERSION=Django==1.8
  - DJANGO_VERSION=Django==1.8.1
  - DJANGO_VERSION=Django==1.8.2
  - DJANGO_VERSION=Django==1.8.3
  - DJANGO_VERSION=Django==1.8.4

# command to install dependencies
install:
  - pip install --use-mirrors -r test-requirements.txt
  - pip install --use-mirrors $DJANGO_VERSION

# command to run tests

script:
  - pep8 feedme
  - python run_tests.py

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.2
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.3
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.4
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.5
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.6
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.7
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.8
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.9
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.10
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.11
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.12
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.13
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.14
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.15
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.2
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.3
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.4
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.5
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.6
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.7
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.8
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.9
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.10
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.11
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.12
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.13
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.14
    - python: "3.4"
      env: DJANGO_VERSION=Django==1.4.15

