language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=Django==1.7
  - DJANGO_VERSION=Django==1.7.1
  - DJANGO_VERSION=Django==1.7.2
  - DJANGO_VERSION=Django==1.7.3
  - DJANGO_VERSION=Django==1.7.4
  - DJANGO_VERSION=Django==1.7.5
  - DJANGO_VERSION=Django==1.7.6
  - DJANGO_VERSION=Django==1.7.7
  - DJANGO_VERSION=Django==1.7.8
  - DJANGO_VERSION=Django==1.7.9
  - DJANGO_VERSION=Django==1.7.10
  - DJANGO_VERSION=Django==1.8
  - DJANGO_VERSION=Django==1.8.1
  - DJANGO_VERSION=Django==1.8.2
  - DJANGO_VERSION=Django==1.8.3
  - DJANGO_VERSION=Django==1.8.4
  - DJANGO_VERSION=Django==1.8.5
  - DJANGO_VERSION=Django==1.9.0

# command to install dependencies
install:
  - pip install --use-mirrors -r test-requirements.txt
  - pip install --use-mirrors $DJANGO_VERSION

# command to run tests

script:
  - pep8 feedme
  - python run_tests.py
